on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build atopile test projects
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Build project-1
        id: test-action-project-1
        uses: ./  # use action in root directory
        with:
          path: 'tests/project-1'
